# Generated by Django 6.0.5 on 2026-05-26 07:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedEmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('emission_date', models.DateField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('emission_factor', models.FloatField(default=1.0)),
                ('co2e', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawDataRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARSED', 'Parsed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('system_type', models.CharField(choices=[('SAP', 'SAP ERP'), ('UTILITY', 'Utility Portal'), ('TRAVEL', 'Travel Platform')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('EDITED', 'Edited'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('user', models.CharField(default='Analyst', max_length=255)),
                ('previous_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.normalizedemission')),
            ],
        ),
        migrations.AddField(
            model_name='normalizedemission',
            name='raw_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingest.rawdatarecord'),
        ),
        migrations.AddField(
            model_name='rawdatarecord',
            name='source_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.sourcesystem'),
        ),
        migrations.AddField(
            model_name='sourcesystem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.tenant'),
        ),
        migrations.AddField(
            model_name='normalizedemission',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.tenant'),
        ),
    ]
